import { Injectable } from '@angular/core';

// TODO: This is a template generated by ionic; remove it once the pattern is established.
@Injectable({
  providedIn: 'root'
})
export class SharedService {

  constructor() { }
}
