export enum FlaggedAttribute {
  NAME = 'NAME',
  DESCRIPTION = 'DESCRIPTION',
  CATEGORY_OR_TYPE = 'CATEGORY_OR_TYPE',
  MAIN_LINK = 'MAIN_LINK',
  OTHER_LINK = 'OTHER_LINK',
  PREFERRED_IMAGE = 'PREFERRED_IMAGE',
  OTHER_IMAGE = 'OTHER_IMAGE',
  PUZZLE = 'PUZZLE',
  ANSWER = 'ANSWER'
}
